FROM node:20 as build
RUN npm install -g pnpm
WORKDIR /app/frontend
COPY package.json ./
RUN pnpm install
COPY . .
RUN pnpm run build

FROM nginx:stable-alpine
COPY --from=build /app/frontend/dist /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf