export const enum KEYS {
  C = 'C',
  V = 'V',
  X = 'X',
  Z = 'Z',
  Y = 'Y',
  A = 'A',
  G = 'G',
  L = 'L',
  F = 'F',
  D = 'D',
  B = 'B',
  P = 'P',
  R = 'R',
  MINUS = '-',
  EQUAL = '=',
  DELETE = 'DELETE',
  UP = 'ARROWUP',
  DOWN = 'ARROWDOWN',
  LEFT = 'ARROWLEFT',
  RIGHT = 'ARROWRIGHT',
  ENTER = 'ENTER',
  SPACE = ' ',
  TAB = 'TAB',
  BACKSPACE = 'BACKSPACE',
  ESC = 'ESCAPE',
  PAGEUP = 'PAGEUP',
  PAGEDOWN = 'PAGEDOWN',
  F5 = 'F5',
}

export const HOTKEY_DOC = [
  {
    type: 'General',
children: [
{ label: 'برش', value: 'Ctrl + X' },
{ label: 'کپی', value: 'Ctrl + C' },
{ label: 'الحاق', value: 'Ctrl + V' },
// { label: 'Quick Copy and Paste', value: 'Ctrl + D' },
{ label: 'انتخاب همه', value: 'Ctrl + A' },
{ label: 'واگرد', value: 'Ctrl + Z' },
{ label: 'بازیابی', value: 'Ctrl + Y' },
{ label: 'حذف', value: 'Delete / Backspace' },
{ label: 'انتخاب چندگانه', value: 'Press and Hold Ctrl or Shift' },
{ label: 'Print', value: 'Ctrl + P' },
{ label: 'Close', value: 'ESC' },
],
  },
  {
    type: 'پیش نمایش',
children: [
{ label: 'پیش نمایش از صفحه اول', value: 'F5' },
{ label: 'پیش نمایش از صفحه فعلی', value: 'Shift + F5' },
{ label: 'به صفحه قبل برو', value: '↑ / ← / PgUp' },
{ label: 'به صفحه بعدی برو', value: '↓ / → / PgDown' },
{ label: 'به صفحه بعدی بروید', value: 'Enter / Space' },
{ label: 'ویرایش', value: 'ESC' },
],
  },
  {
    type: 'ویرایش صفحه',
children: [
{ label: 'صفحه جدید', value: 'Enter' },
{ label: 'حرکت بوم', value: 'Space + Mouse Drag' },
{ label: 'زوم', value: 'Ctrl + Mouse Wheel' },
{ label: 'بزگنمایی بوم', value: 'Ctrl + =' },
{ label: 'کوچکنمایی بوم', value: 'Ctrl + -' },
{ label: 'متناسب با صفحه نمایش', value: 'Ctrl + 0' },
{ label: 'صفحه قبلی (عنصر انتخاب نشده)', value: '↑ / ←' },
{ label: 'صفحه بعدی (عنصر انتخاب نشده)', value: '↓ / →' },
{ label: 'صفحه قبلی', value: 'Mouse Up / PgUp' },
{ label: 'صفحه بعدی', value: 'Mouse Down / PgDown' },
],
  },
  {
    type: 'عملیات عنصر',
children: [
{ label: 'حرکت کنید', value: '↑ / ← / ↓ / →' },
{ label: 'قفل', value: 'Ctrl + L' },
{ label: 'ادغام', value: 'Ctrl + G' },
{ label: 'لغو ادغام', value: 'Ctrl + Shift + G' },
{ label: 'ارسال به جلو', value: 'Alt + F' },
{ label: 'ارسال به پشت', value: 'Alt + B' },
{ label: 'قفل نسبت ابعاد', value: 'Press Ctrl or Shift' },
{ label: 'خط افقی / عمودی ایجاد کنید', value: 'Press Ctrl or Shift' },
{ label: 'تغییر عنصر فوکوس', value: 'Tab' },
{ label: 'برش تصویر را تایید کنید', value: 'Enter' },
],
  },
  {
    type: 'Table Edit',
children: [
{ label: 'Focus on the next cell', value: 'Tab' },
{ label: 'Insert a row above', value: 'Ctrl + ↑' },
{ label: 'Insert a row below', value: 'Ctrl + ↓' },
{ label: 'Insert a column on the left', value: 'Ctrl + ←' },
{ label: 'Insert a column on the right', value: 'Ctrl + →' },
],
  },
  // {
// type: 'Chart data editing',
// children: [
// { label: 'Focus on the next line', value: 'Enter' },
// ],
// },
{
type: 'ویرایش متن',
children: [
{ label: 'پررنگ', value: 'Ctrl + B' },
{ label: 'خمیده', value: 'Ctrl + I' },
{ label: 'زیر خط', value: 'Ctrl + U' },
{ label: 'ضربه زدن', value: 'Ctrl + D' },
],
},
]